FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libpq-dev gcc
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# On lance ton script d'ingestion au démarrage
CMD ["python", "src/ingestion/zeek_stream.py"]